name: user_repository
description: Dart package which manages the user domain.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  authentication_client:
    path: ../authentication_client/authentication_client
  equatable: ^2.0.5

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.24.3
  very_good_analysis: ^5.0.0
