name: magic_yeti
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analytics_repository:
   path: packages/analytics_repository
  app_ui:
    path: packages/app_ui
  bloc: ^8.1.2
  equatable: ^2.0.5
  firebase_authentication_client:
    path: packages/authentication_client/firebase_authentication_client
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  form_inputs:
    path: packages/form_inputs
  go_router: ^10.0.0
  intl: ^0.18.0
  provider: ^6.0.5
  user_repository:
    path: packages/user_repository

dev_dependencies:
  bloc_test: ^9.1.2
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
