// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'card.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Card _$CardFromJson(Map<String, dynamic> json) => Card(
      object: json['object'] as String,
      id: json['id'] as String,
      set: json['set'] as String,
      oracleId: json['oracleId'] as String,
      multiverseIds: (json['multiverseIds'] as List<dynamic>)
          .map((e) => e as int)
          .toList(),
      tcgPlayerId: json['tcgPlayerId'] as int,
      cardMarketId: json['cardMarketId'] as int,
      name: json['name'] as String,
      lang: json['lang'] as String,
      releasedAt: json['releasedAt'] as String,
      uri: json['uri'] as String,
      scryfallUri: json['scryfallUri'] as String,
      layout: json['layout'] as String,
      highResImage: json['highResImage'] as bool,
      imageStatus: json['imageStatus'] as String,
      imageUris: ImageURIs.fromJson(json['imageUris'] as Map<String, dynamic>),
      manaCost: json['manaCost'] as String,
      cmc: json['cmc'] as int,
      typeLine: json['typeLine'] as String,
      oracleText: json['oracleText'] as String,
      colors:
          (json['colors'] as List<dynamic>).map((e) => e as String).toList(),
      colorIdentity: (json['colorIdentity'] as List<dynamic>)
          .map((e) => e as String)
          .toList(),
      keywords:
          (json['keywords'] as List<dynamic>).map((e) => e as String).toList(),
      legalities:
          Legalities.fromJson(json['legalities'] as Map<String, dynamic>),
      games: (json['games'] as List<dynamic>).map((e) => e as String).toList(),
      reserved: json['reserved'] as bool,
      foil: json['foil'] as bool,
      nonfoil: json['nonfoil'] as bool,
      finishes:
          (json['finishes'] as List<dynamic>).map((e) => e as String).toList(),
      oversized: json['oversized'] as bool,
      promo: json['promo'] as bool,
      reprint: json['reprint'] as bool,
      variation: json['variation'] as bool,
      setId: json['setId'] as String,
      setName: json['setName'] as String,
      setType: json['setType'] as String,
      setUri: json['setUri'] as String,
      setSearchUri: json['setSearchUri'] as String,
      scryfallSetUri: json['scryfallSetUri'] as String,
      rulingsUri: json['rulingsUri'] as String,
      printsSearchUri: json['printsSearchUri'] as String,
      collectorNumber: json['collectorNumber'] as String,
      digital: json['digital'] as bool,
      rarity: json['rarity'] as String,
      cardBackId: json['cardBackId'] as String,
      artist: json['artist'] as String,
      artistIds:
          (json['artistIds'] as List<dynamic>).map((e) => e as String).toList(),
      illustrationId: json['illustrationId'] as String,
      borderColor: json['borderColor'] as String,
      frame: json['frame'] as String,
      securityStamp: json['securityStamp'] as String,
      fullArt: json['fullArt'] as bool,
      textless: json['textless'] as bool,
      booster: json['booster'] as bool,
      storySpotlight: json['storySpotlight'] as bool,
      edhrecRank: json['edhrecRank'] as int,
      pennyRank: json['pennyRank'] as int,
      prices: Prices.fromJson(json['prices'] as Map<String, dynamic>),
      relatedUris:
          RelatedURIs.fromJson(json['relatedUris'] as Map<String, dynamic>),
      purchaseUris:
          PurchaseURIs.fromJson(json['purchaseUris'] as Map<String, dynamic>),
    );

Map<String, dynamic> _$CardToJson(Card instance) => <String, dynamic>{
      'object': instance.object,
      'id': instance.id,
      'oracleId': instance.oracleId,
      'multiverseIds': instance.multiverseIds,
      'tcgPlayerId': instance.tcgPlayerId,
      'cardMarketId': instance.cardMarketId,
      'name': instance.name,
      'lang': instance.lang,
      'releasedAt': instance.releasedAt,
      'uri': instance.uri,
      'scryfallUri': instance.scryfallUri,
      'layout': instance.layout,
      'highResImage': instance.highResImage,
      'imageStatus': instance.imageStatus,
      'imageUris': instance.imageUris.toJson(),
      'manaCost': instance.manaCost,
      'cmc': instance.cmc,
      'typeLine': instance.typeLine,
      'oracleText': instance.oracleText,
      'colors': instance.colors,
      'colorIdentity': instance.colorIdentity,
      'keywords': instance.keywords,
      'legalities': instance.legalities.toJson(),
      'games': instance.games,
      'reserved': instance.reserved,
      'foil': instance.foil,
      'nonfoil': instance.nonfoil,
      'finishes': instance.finishes,
      'oversized': instance.oversized,
      'promo': instance.promo,
      'reprint': instance.reprint,
      'variation': instance.variation,
      'setId': instance.setId,
      'set': instance.set,
      'setName': instance.setName,
      'setType': instance.setType,
      'setUri': instance.setUri,
      'setSearchUri': instance.setSearchUri,
      'scryfallSetUri': instance.scryfallSetUri,
      'rulingsUri': instance.rulingsUri,
      'printsSearchUri': instance.printsSearchUri,
      'collectorNumber': instance.collectorNumber,
      'digital': instance.digital,
      'rarity': instance.rarity,
      'cardBackId': instance.cardBackId,
      'artist': instance.artist,
      'artistIds': instance.artistIds,
      'illustrationId': instance.illustrationId,
      'borderColor': instance.borderColor,
      'frame': instance.frame,
      'securityStamp': instance.securityStamp,
      'fullArt': instance.fullArt,
      'textless': instance.textless,
      'booster': instance.booster,
      'storySpotlight': instance.storySpotlight,
      'edhrecRank': instance.edhrecRank,
      'pennyRank': instance.pennyRank,
      'prices': instance.prices.toJson(),
      'relatedUris': instance.relatedUris.toJson(),
      'purchaseUris': instance.purchaseUris.toJson(),
    };
